# Generated by Django 5.0.3 on 2024-05-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mesa_producto_pedido_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numeroPedido',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
