# Generated by Django 5.0.3 on 2024-05-21 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_factura_idpedido_factura_cosaspedidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='idMesero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='mesa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.mesa'),
            preserve_default=False,
        ),
    ]
